output directory: temp/1192
implementation directory: /quic/aioquic
implementation command: python3 examples/http3_client.py -v  -i --insecure --legacy-http https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html
../quic_client_test_version_negociation (0) ...
implementation command: sleep 5; python3 examples/http3_client.py --version_negociation -l /results/temp/aioquic_key.log -v -q /results/temp/aioquic_key.log/ --ca-certs tests/pycacert.pem -i --insecure --legacy-http https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html https://localhost:4443/index.html
quic_process pid: 13030
timeout 100 ./build/quic_client_test_version_negociation seed=597 the_cid=0 
terminating client process 13032
Traceback (most recent call last):
  File "test.py", line 420, in <module>
    status = test.run(test_command)
  File "test.py", line 255, in run
    status = self.run_expect(test_command)
  File "test.py", line 286, in run_expect
    ok = self.expect(test_command,iev)
  File "test.py", line 313, in expect
    proc.terminate()
  File "/usr/lib/python2.7/subprocess.py", line 1274, in terminate
    self.send_signal(signal.SIGTERM)
  File "/usr/lib/python2.7/subprocess.py", line 1269, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process
